import { Button, HorizontalBox, VerticalBox, TextEdit, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    default-font-size: 20px;
    VerticalBox {
        Text {
            text: "This is a test app using " + Platform.style-name;
        }
        LineEdit {
            placeholder-text: "Enter search term";
            text: "Test";
//            input-type: search;
            accepted(txt) => { lineEdit.text = "Searching for" + txt; }
        }
        HorizontalBox {
            Text {
                text: "Some text here to test lineEdits with lack of room";
            }
            lineEdit := LineEdit {
                placeholder-text: "This is a long placeholder";
                text: "Hello world with Slint";
            }
        }
        LineEdit {
            text: "password";
            input-type: password;
        }
        LineEdit {
            text: "1234";
            input-type: number;
        }
        LineEdit {
            text: "12.34";
            input-type: decimal;
        }

        TextEdit {
            font-size: 14px;
            text: "Lorem ipsum dolor sit amet,\n consectetur adipisici elit";
        }
    }
}
