import { Button, HorizontalBox, VerticalBox, TextEdit, LineEdit } from "std-widgets.slint";
import { DetailsWindow } from "details-window.slint";

export component AppWindow inherits Window {
    default-font-size: 20px;
    property <string> clicked-film-name;
    VerticalBox {
        Text {
            text: "This is a test app using " + Platform.style-name;
        }
        LineEdit {
            text: "Press Enter in this field";
            accepted(txt) => { 
                root.clicked-film-name = "Selected film";
                detailsWindow.show();
            }
        }

        TextEdit {
            font-size: 14px;
            text: "";
        }
    }
    detailsWindow := DetailsWindow {
        film-name: root.clicked-film-name;
        visible: false;
        width: root.width;                                                                                      height: root.height;
    }
}
